// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tngdedahfmtfkzjvyrnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZ2RlZGFoZm10Zmt6anZ5cm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTc3MTMsImV4cCI6MjA3MzQzMzcxM30.uqfKOe5w2dyXTEWi5U4s99S5NThHGtZaidKgR_8f4U8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});